config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  # Generate only tracks#new under albums#new
  resources :albums, except: [:new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  live       :boolean
#

class Album < ApplicationRecord
  validates :band_id, :name, presence: true

  belongs_to :band
  has_many :tracks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  album_id   :integer          not null
#  lyrics     :text
#  bonus      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :album_id, :name, presence: true

  belongs_to :album
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  attr_reader :password

  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
    @all_bands = Band.all
    @band = Band.find(params[:band_id])
  end

  def create
    album = Album.new(album_params)

    if album.save
      redirect_to album_url(album)
    else
      flash[:errors] << album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    @tracks = @album.tracks
  end

  private

  def album_params
    params.require(:album).permit(:name, :band_id, :live)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login!(user)
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    @band = Band.new
  end

  def create
    band = Band.new(band_params)

    if band.save
      redirect_to band_url(band)
    else
      flash[:errors] << band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = this_band
  end

  def update
    @band = this_band

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def index
    @bands = Band.all
  end

  def show
    @band = this_band
  end

  private

  def this_band
    Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user
      login!(user)
      redirect_to user_url(user)
    else
      flash[:errors] = ["Email or password was incorrect"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @track = Track.new
    @all_albums = Album.all
    @album = Album.find(params[:album_id])
  end

  def create
    track = Track.create(track_params)

    if track.save
      redirect_to track_url(track)
    else
      flash[:errors] << track.errors.full_messages
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
  end

  private

  def track_params
    params.require(:track).permit(:name, :album_id, :lyrics, :bonus)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      login!(user)
      redirect_to user_url(user)
    else
      flash[:errors] = user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type=\"hidden\"
     name=\"authenticity_token\"
      value=\"#{form_authenticity_token}\">".html_safe
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_album.html.erb
<a href="<%= album_url(album.id) %>"><%= album.name %></a>
<br>

app/views/albums/new.html.erb
<h1>Create an Album</h1>

<form action="<%= albums_url %>" method="post">
  <%= auth_token %>

  <label for="band">Band</label>
  <select id="band" name="album[band_id]">
    <% @all_bands.try(:each) do |band| %>
    <option value="<%= band.id%>" <%= 'selected' if @band.id == band.id %> ><%= band.name %></option>
    <% end %>
  </select>

  <br>

  <label for="name">Album Name</label>
  <input id="name" type="text" name="album[name]" value="">

  <br>

  Live?:
  <input id="live_true" type="radio" name="album[live]" value="true" checked>
  <label for="live_true">Yes</label>
  <input id="live_false" type="radio" name="album[live]" value="false">
  <label for="live_false">No</label>

  <br>

  <input type="submit" name="" value="Create Album">
</form>

app/views/albums/show.html.erb
<h1><%= render 'bands/link', band: @album.band %>
  / <%= @album.name %></h1>

Recording Type: <%= @album.live? ? "Live" : "Studio" %>

<br><br>

<%= button_to "Add a Track", new_album_track_url(@album), method: :get %>

<br>

<!-- Show all tracks -->
<%= render @tracks %>

app/views/bands/_band.html.erb
<a href="<%= band_url(band.id) %>"><%= band.name %></a>
<br>

app/views/bands/_form.html.erb
<%
  if band.id.nil?
    _method = "POST"
    _action = bands_url
    _text = "Create Band"
  else
    _method = "PATCH"
    _action = band_url(band)
    _text = "Update Band"
  end
%>

<h1><%= _text %></h1>

<form action="<%= _action %>" method="post">
  <%= auth_token %>

  <input type="hidden" name="_method" value="<%= _method %>">

  <label for="name">Band Name</label>
  <input id="name" type="text" name="band[name]" value="<%= @band.name %>">

  <input type="submit" name="" value="<%= _text %>">
</form>

app/views/bands/_link.html.erb
<a href="<%= band_url(band) %>"><%= band.name %></a>

app/views/bands/edit.html.erb
<%= render 'form', band: @band %>

app/views/bands/index.html.erb
<h1>All Bands</h1>

<%= button_to "Create a Band", new_band_url, method: :get %>

<br>

<%= render @bands %>

app/views/bands/new.html.erb
<h1>Create a band</h1>

<form action="<%= bands_url%>" method="post">
  <%= auth_token %>

  <label for="name">Band Name</label>
  <input id="name" type="text" name="band[name]" value="">

  <input type="submit" name="" value="Create Band">
</form>

app/views/bands/show.html.erb
<h1><%= link_to "All Bands", bands_url, method: :get %> / <%= @band.name %></h1>

<%= button_to "Create an Album", new_band_album_url(@band), method: :get %>
<%= button_to "Update Band", edit_band_url(@band), method: :get %>

<br>

<!-- Show all Albums -->

<%= render @band.albums %>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/user_header' %>
    <%= render 'shared/flash' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash[:errors].try(:each) do |error| %>
  <div>
    <%= error %>
  </div>
<% end %>

app/views/shared/_user_form.html.erb
<% action = (type == :sign_up ? user_url : session_url) %>
<% button = (type == :sign_up ? "Sign Up" : "Sign In" ) %>

<form action="<%= action %>" method="post">
  <%= auth_token %>

  <label for="email">Email</label>
  <input id="email" type="text" name="user[email]" value="">

  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]" value="">

  <input type="submit" name="" value="Sign In">
</form>

app/views/shared/_user_header.html.erb
<% if current_user %>
  <header>
    Logged in as <%= current_user.email %>
    <%= button_to "Log Out", session_url, method: :delete %>
  </header>
<% else %>
  <head>

  </head>
<% end %>

app/views/tracks/_track.html.erb
<a href="<%= track_url(track)%>"><%= track.name%></a>
<br>

app/views/tracks/new.html.erb
<h1><%= @album.name %> : Create New Track</h1>

<form class="" action="<%= tracks_url %>" method="post">
  <%= auth_token %>

  <label for="album">Album</label>
  <select id="album" name="track[album_id]">
    <% @all_albums.try(:each) do |album| %>
    <option value="<%= album.id%>" <%= 'selected' if @album.id == album.id %> ><%= album.name %></option>
    <% end %>
  </select>

  <br>

  Bonus Track?
  <input id="bonus_true" type="radio" name="track[bonus]" value="false" checked>
  <label for="bonus_true">No</label>
  <input id="bonus_false" type="radio" name="track[bonus]" value="true">
  <label for="bonus_false">Yes</label>

  <br>

  <label for="name">Track Name</label>
  <input id="name" type="text" name="track[name]" value="">

  <br>

  Lyrics
  <br>
  <textarea name="track[lyrics]" rows="8" cols="80"></textarea>

  <br>

  <input type="submit" name="" value="Add Track">

</form>

app/views/tracks/show.html.erb
<h1><%= @track.album.name %> / <%= @track.name %></h1>

Bonus Track? <%= @track.bonus? ? "Yes" : "No" %>
<br>
Lyrics
<p> <%= @track.lyrics %></p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label for="email">Email</label>
  <input id="email" type="text" name="user[email]" value="">

  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]" value="">

  <input type="submit" name="" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1>User Page</h1>

email: <%= @user.email %>